// @vue/Box.vue
<script setup>
    import "../assets/skin.css"
    import "../assets/container.css"
    import { ref } from "vue"

    const props = defineProps
    ({ 
        skin: {type: String, required: false, default: "platinum"},
        width: {type: String, required: false, default: "max-content"},
        height: {type: String, required: false, default: "max-content"},
        margin: {type: String, required: false, default: "1.5em"},
        padding: {type: String, required: false, default: "1em"},
        row: {type: Boolean, required: false, default: false}
    })

    const rowClass = ref("")
    if(props.row) { rowClass.value = "boxRowLayout" }
</script>

<template>
    <div id="box" :class="`${props.skin} ${rowClass}`" :style="`height:${props.height};width:${props.width};margin:${props.margin};padding:${props.padding};`" >
        <slot />
    </div>
</template>

// @svelte/Box.svelte
<script>
    import "../assets/skin.css"
    import "../assets/container.css"
    export let skin = "platinum"
    export let width = "max-content"
    export let height = "max-content"
    export let margin = "1.5em"
    export let padding = "1em"
    export let row = false

    let rowClass = ""
    $: if(row) { rowClass = "boxRowLayout" }
</script>

<div id="box" class="{skin} {rowClass}" style="height:{height};width:{width};margin:{margin};padding:{padding};" >
    <slot />
</div>
