// @svelte/Card.svelte
<script>
    import "../assets/skin.css"
    import "../assets/container.css"
    export let skin = "platinum"
    export let link = null
    export let image = null
    export let imagePosition = "left"
    export let width = "max-content"
    export let height = "max-content"
    export let margin = "1.5em"
    
    let posClass = ""
    if(image && imagePosition=="top") { posClass = "imgOnTop" }
    else if(image && imagePosition=="right") { posClass = "imgOnRight" }
    else if(image && imagePosition=="bottom") { posClass = "imgOnBottom" }
    else if(image && imagePosition=="left"){ posClass = "imgOnLeft" }
</script>

{#if link}
    <a href={link} id="card" class="{skin} {posClass}" style="height:{height};width:{width};margin:{margin};">
        {#if image && (imagePosition=="left" || imagePosition=="top")}
            <div class="cardThumb" style="background-image:url({image});"></div>
        {/if}
        
        <div class="cardInner"><slot /></div>

        {#if image && (imagePosition=="right" || imagePosition=="bottom")}
            <div class="cardThumb" style="background-image:url({image});"></div>
        {/if}
    </a>
{:else}
    <div id="card" class="{skin} {posClass}" style="height:{height};width:{width};margin:{margin};">
        {#if image && (imagePosition=="left" || imagePosition=="top")}
            <div class="cardThumb" style="background-image:url({image});"></div>
        {/if}
        
        <div class="cardInner"><slot /></div>

        {#if image && (imagePosition=="right" || imagePosition=="bottom")}
            <div class="cardThumb" style="background-image:url({image});"></div>
        {/if}
    </div>
{/if}

// @vue/Card.vue
<script setup>
    import "../assets/skin.css"
    import "../assets/container.css"
    import { ref } from "vue"

    const props = defineProps
    ({ 
        skin: {type: String, required: false, default: "platinum"},
        link: {type: String, required: false, default: null},
        image: {type: String, required: false, default: null},
        imagePosition: {type: String, required: false, default: "left"},
        width: {type: String, required: false, default: "max-content"},
        height: {type: String, required: false, default: "max-content"},
        margin: {type: String, required: false, default: "1.5em"}
    })

    const posClass = ref("")
    if(props.image && props.imagePosition=="top") { posClass.value = "imgOnTop" }
    else if(props.image && props.imagePosition=="right") { posClass.value = "imgOnRight" }
    else if(props.image && props.imagePosition=="bottom") { posClass.value = "imgOnBottom" }
    else if(props.image && props.imagePosition=="left"){ posClass.value = "imgOnLeft" }
</script>

<template>
    <a v-if="link" :href="link" id="card" :class="`${props.skin} ${posClass}`" :style="`height:${props.height};width:${props.width};margin:${props.margin};`" >
        <div v-if="image && (imagePosition=='left' || imagePosition=='top')" class="cardThumb" :style="`background-image:url(${image});`"></div>
        <div class="cardInner"><slot /></div>
        <div v-if="image && (imagePosition=='right' || imagePosition=='bottom')" class="cardThumb" :style="`background-image:url(${image});`"></div>
    </a>
    <div v-else id="card" :class="`${props.skin} ${posClass}`" :style="`height:${props.height};width:${props.width};margin:${props.margin};`" >
        <div v-if="image && (imagePosition=='left' || imagePosition=='top')" class="cardThumb" :style="`background-image:url(${image});`"></div>
        <div class="cardInner"><slot /></div>
        <div v-if="image && (imagePosition=='right' || imagePosition=='bottom')" class="cardThumb" :style="`background-image:url(${image});`"></div>
    </div>
</template>
