// @svelte/Box.svelte
<script>
    import "../assets/skin.css"
    import "../assets/container.css"
    export let skin = "platinum"
    export let width = "max-content"
    export let height = "max-content"
    export let margin = "1.5em"
    export let padding = "1em"
    export let row = false

    let rowClass = ""
    $: if(row) { rowClass = "boxRowLayout" }
</script>

<div id="box" class="{skin} {rowClass}" style="height:{height};width:{width};margin:{margin};padding:{padding};" >
    <slot />
</div>

// @react/Box.jsx
import "../assets/skin.css"
import "../assets/container.css"
import { useState, useEffect } from "react"

export default function Box({
      skin = "platinum",
      width = "max-content",
      height = "max-content",
      margin = "1.5em",
      padding = "1em",
      row = false,
      children
    }){

  const [rowClass, setRowClass] = useState("")
  useEffect(() => {
    if(row) { setRowClass("boxRowLayout") }
  }, [])

  return ( 
    <div id="box" className={`${skin} ${rowClass}`} style={{height: height, width: width, margin: margin, padding: padding}} >
      {children}
    </div>
  )
}
