// @svelte/Button.svelte
<script>
    import "../assets/skin.css"
    import "../assets/button.css"
    export let text = "Button"
    export let link = "/"
    export let shape = "hex"
    export let skin = "platinum"
</script>
  
<a href={link} id={shape} class="btnOuter {skin}">
    
    <!-- shape: wedge -->
    {#if shape=="wedge"}
        <div class="btnInner">{text}</div>
    
    <!-- shape: hex (fallback) -->
    {:else}
        <span class="pt">
            <div></div><div></div>
        </span>
        
        <div class="btnInner">
            <div><div class="fill">{text}</div></div>
        </div>
        
        <span class="pt">
            <div></div><div></div>
        </span>
    {/if}
</a>

// @react/Button.jsx
import "../assets/skin.css"
import "../assets/button.css"

export default function Button({ 
    text = "Button",
    link = "/",
    shape = "hex",
    skin = "platinum"
  }){

  return ( 
    <a href={link} id={shape} className={"btnOuter " + skin}>

      {/* shape: wedge */}
      {shape === "wedge" && <div className="btnInner">{text}</div>}
      
      {/* shape: hex (fallback) */}
      {shape === "hex" && 
        <span className="pt">
          <div></div><div></div>
        </span>
      }
      {shape === "hex" && 
        <div className="btnInner">
          <div><div className="fill">{text}</div></div>
        </div>
      }
      {shape === "hex" && 
        <span className="pt">
          <div></div><div></div>
        </span>
      }

    </a>
  )
}
